# Utiliser une image Node.js comme base
FROM node:14

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et installer les dépendances
COPY ./frontend/package.json /app/
RUN npm install

# Copier le code du frontend
COPY ./frontend /app

# Exposer le port pour le frontend (par défaut, 3000 pour React)
EXPOSE 3000

# Commande pour démarrer l'application frontend
CMD ["npm", "start"]